export const species = [
  {
    id: "kyu-korisato",
    name: "旧氷砂糖",
    scientific: "Haworthia turgida f. variegata",
    type: "園芸種",
    accent: "#d4e8d8",
    description: "白い斑（白斑）が入った軟葉系ハオルチア。白と緑のまだら模様が特徴で、「氷砂糖」の名の通り白くキラキラした見た目を持つ。",
    water: "春・秋は週1回程度。夏・冬は月1〜2回に控える。根腐れに注意。",
    temperature: "5〜35℃。霜に当てないよう注意する。",
    placement: "直射日光を避けた明るい窓辺。レースカーテン越しが理想。",
    soil: "水はけの良い多肉植物用土。軽石や鹿沼土を3割ほど混ぜると良い。",
    light: "良い",
    lightBar: 65,
    lightDesc: "明るい間接光（3000〜5000lux）",
    breeding: null,
    gallery: [],
  },
  {
    id: "seiun-no-mai",
    name: "青雲の舞",
    scientific: "Haworthia vittata",
    type: "原種",
    accent: "#c8dfc8",
    description: "三角形の緑の葉に白い縦縞（窓）が走る原種。逆光で縦筋が透けて見える美しさが魅力。やや硬めの葉質で丈夫。",
    water: "春・秋は週1回程度。夏・冬は乾燥気味に管理する。",
    temperature: "5〜35℃。高温多湿に注意。通気を確保する。",
    placement: "明るい間接光の当たる場所。通気の良い環境が好ましい。",
    soil: "軽石多めの水はけ重視の配合土。水はけが最重要。",
    light: "非常に良い",
    lightBar: 85,
    lightDesc: "明るい間接光〜弱い直射（3000〜8000lux）",
    breeding: null,
    gallery: [],
  },
  {
    id: "cymbiformis",
    name: "シンビフォルミス",
    scientific: "Haworthia cymbiformis",
    type: "原種",
    accent: "#d8eedd",
    description: "船形の柔らかい葉を持つ原種。葉先に透明な窓があり明るい黄緑色が特徴。透明感が高く初心者にも人気の品種。",
    water: "春・秋は週1回程度。比較的水を好むが過湿は禁物。",
    temperature: "5〜35℃。丈夫で育てやすい。",
    placement: "半日陰〜明るい窓辺。適応力が高く育てやすい。",
    soil: "多肉植物用土。やや保水性のある配合でも対応できる。",
    light: "普通",
    lightBar: 55,
    lightDesc: "半日陰〜明るい間接光（2000〜5000lux）",
    breeding: null,
    gallery: [],
  },
  {
    id: "umbraticola",
    name: "ウンブラティコーラ",
    scientific: "Haworthia umbraticola",
    type: "原種",
    accent: "#b8d4bc",
    description: "日陰を好む性質を持つコンパクトな原種。やや硬めの葉質で、葉に白い模様や突起（テスタ）がある。",
    water: "春・秋は10日に1回程度。乾燥気味に管理する。",
    temperature: "5〜30℃。高温に比較的弱いので夏は涼しい場所へ。",
    placement: "半日陰〜日陰。直射日光は葉焼けの原因になるので避ける。",
    soil: "水はけの良い多肉植物用土。軽石を多めに。",
    light: "足りない〜普通",
    lightBar: 35,
    lightDesc: "半日陰（1000〜3000lux）",
    breeding: null,
    gallery: [],
  },
];
