export const species = [
  {
    id: "kyu-korisato",
    name: "旧氷砂糖",
    scientific: "Haworthia turgida f. variegata",
    type: "園芸種",
    accent: "#d4e8d8",
    description: "白い斑（白斑）が入った軟葉系ハオルチア。白と緑のまだら模様が特徴で、「氷砂糖」の名の通り白くキラキラした見た目を持つ。",
    water: "春・秋は週1回程度。夏・冬は月1〜2回に控える。根腐れに注意。",
    temperature: "5〜35℃。霜に当てないよう注意する。",
    placement: "直射日光を避けた明るい窓辺。レースカーテン越しが理想。",
    soil: "水はけの良い多肉植物用土。軽石や鹿沼土を3割ほど混ぜると良い。",
    light: "良い",
    lightBar: 65,
    lightDesc: "明るい間接光（3000〜5000lux）",
    breeding: null,
    gallery: [],
  },
  {
    id: "seiun-no-mai",
    name: "青雲の舞",
    scientific: "Haworthia vittata",
    type: "原種",
    accent: "#c8dfc8",
    description: "三角形の緑の葉に白い縦縞（窓）が走る原種。逆光で縦筋が透けて見える美しさが魅力。やや硬めの葉質で丈夫。",
    water: "春・秋は週1回程度。夏・冬は乾燥気味に管理する。",
    temperature: "5〜35℃。高温多湿に注意。通気を確保する。",
    placement: "明るい間接光の当たる場所。通気の良い環境が好ましい。",
    soil: "軽石多めの水はけ重視の配合土。水はけが最重要。",
    light: "非常に良い",
    lightBar: 85,
    lightDesc: "明るい間接光〜弱い直射（3000〜8000lux）",
    breeding: null,
    gallery: [],
  },
  {
    id: "cymbiformis",
    name: "シンビフォルミス",
    scientific: "Haworthia cymbiformis",
    type: "原種",
    accent: "#d8eedd",
    description: "船形の柔らかい葉を持つ原種。葉先に透明な窓があり明るい黄緑色が特徴。透明感が高く初心者にも人気の品種。",
    water: "春・秋は週1回程度。比較的水を好むが過湿は禁物。",
    temperature: "5〜35℃。丈夫で育てやすい。",
    placement: "半日陰〜明るい窓辺。適応力が高く育てやすい。",
    soil: "多肉植物用土。やや保水性のある配合でも対応できる。",
    light: "普通",
    lightBar: 55,
    lightDesc: "半日陰〜明るい間接光（2000〜5000lux）",
    breeding: null,
    gallery: [],
  },
  {
    id: "umbraticola",
    name: "ウンブラティコーラ",
    scientific: "Haworthia umbraticola",
    type: "原種",
    accent: "#b8d4bc",
    description: "日陰を好む性質を持つコンパクトな原種。やや硬めの葉質で、葉に白い模様や突起（テスタ）がある。",
    water: "春・秋は10日に1回程度。乾燥気味に管理する。",
    temperature: "5〜30℃。高温に比較的弱いので夏は涼しい場所へ。",
    placement: "半日陰〜日陰。直射日光は葉焼けの原因になるので避ける。",
    soil: "水はけの良い多肉植物用土。軽石を多めに。",
    light: "足りない〜普通",
    lightBar: 35,
    lightDesc: "半日陰（1000〜3000lux）",
    breeding: null,
    gallery: [],
  },
  {
    id: "milky-cloud",
    name: "ミルキークラウド",
    scientific: "Haworthia 'Milky Cloud'",
    type: "園芸種",
    accent: "#e8f0e8",
    description: "白みがかった乳白色の窓をもつ軟葉系ハオルチア。雲のように淡く霞む窓面が特徴で、光にかざすと柔らかな透明感が際立つ。",
    water: "春・秋は土が乾いたら週1回程度。夏・冬は月1〜2回に減らし乾燥気味に管理。",
    temperature: "15〜20℃が理想。冬は5℃以上を保つ。室内管理推奨。",
    placement: "明るい室内の窓辺。直射日光は避け、レースカーテン越しの光が最適。",
    soil: "多肉植物用培養土。赤玉土小粒・鹿沼土・川砂などを混ぜた水はけ良い配合。",
    light: "足りない〜普通",
    lightBar: 35,
    lightDesc: "室内明るい窓辺の間接光（500〜3000lux）",
    breeding: null,
    gallery: [],
  },
  {
    id: "hikaru-obtusa",
    name: "光オブツーサ",
    scientific: "Haworthia obtusa（選抜品種）",
    type: "園芸種",
    accent: "#d0ecd8",
    description: "オブツーサの中でも特に窓の透明度が高く光を強く反射する選抜品種。光を当てると窓がレンズのように輝く。",
    water: "春・秋は月2〜3回。夏・冬は月1〜2回、器の半分程度の量を目安に。",
    temperature: "15〜20℃が理想。冬は5℃以下にならないよう室内管理。",
    placement: "明るい室内の窓辺か半日陰。強光で窓が曇るため遮光50%程度が理想。",
    soil: "多肉植物用土または赤玉土・軽石・腐葉土の水はけ重視配合。",
    light: "足りない〜普通",
    lightBar: 30,
    lightDesc: "過度な光は窓の透明度を損なうため低め管理（500〜2500lux）",
    breeding: null,
    gallery: [],
  },
  {
    id: "murasaki-obtusa",
    name: "紫オブツーサ",
    scientific: "Haworthia obtusa（選抜品種）",
    type: "園芸種",
    accent: "#d8cce8",
    description: "光や温度変化で葉全体が深い紫〜黒紫に色づくオブツーサ。窓の透明度も高く、ダークカラーと透明感のコントラストが魅力。",
    water: "生育期（春・秋）は土が乾いたら週1回たっぷり。夏・冬は頻度を落とし乾燥気味に。",
    temperature: "15〜20℃が理想。昼夜の寒暖差があると紫色が鮮やかに出やすい。",
    placement: "室内明るい窓辺。発色には適度な光が必要。夏は直射日光を避ける。",
    soil: "多肉植物用培養土。水はけ重視で軽石や鹿沼土を混合するとよい。",
    light: "普通",
    lightBar: 45,
    lightDesc: "紫の発色には適度な光が必要（1000〜5000lux）",
    breeding: null,
    gallery: [],
  },
  {
    id: "suichuu-getsu",
    name: "水中月",
    scientific: "Haworthia 'Shui Zhong Yue'",
    type: "園芸種",
    accent: "#dce8dc",
    description: "格子状の暗窓に映えるアイボリー〜黄色の斑が美しい斑入りオブツーサ。「水に映る月」の名にふさわしい幻想的な外観。",
    water: "土が乾いたらたっぷり与える。夏は断水気味でも可。過湿は徒長・根腐れの原因になるため注意。",
    temperature: "15〜20℃が理想。冬は5℃以上を保ち室内管理。",
    placement: "明るい室内の窓辺。直射日光は避けレースカーテン越し程度の光が適切。",
    soil: "多肉植物用土か赤玉土・鹿沼土・川砂などの水はけの良い用土。根が深いため高さのある鉢を推奨。",
    light: "足りない〜普通",
    lightBar: 35,
    lightDesc: "室内間接光（500〜3000lux）",
    breeding: null,
    gallery: [],
  },
  {
    id: "nortieri",
    name: "ノリピア",
    scientific: "Haworthia nortieri",
    type: "原種",
    accent: "#ccdccc",
    description: "南アフリカ・セダーバーグ原産の小型軟葉系原種。柔らかい葉に半透明の斑点が散りばめられ、淡緑〜淡紫色を帯びた繊細な美しさ。",
    water: "春・秋の生育期は土が乾いたらたっぷり。夏・冬は月1〜2回程度に控える。",
    temperature: "15〜20℃が理想。冬は5℃以上を保つ（霜は避ける）。",
    placement: "明るい半日陰。屋外では遮光50〜60%。室内の明るい窓辺でも可。",
    soil: "水はけのよい多肉植物用土。赤玉土・軽石・川砂を混合した砂礫質の配合が向く。",
    light: "普通",
    lightBar: 50,
    lightDesc: "明るい半日陰（1000〜5000lux）",
    breeding: null,
    gallery: [],
  },
  {
    id: "cooperi-gracilis",
    name: "クーペリー var.グラキリス",
    scientific: "Haworthia cooperi var. gracilis",
    type: "原種",
    accent: "#c8e0d0",
    description: "クーペリーの変種で葉が細くスリムなのが特徴。半透明の窓をもつ軟葉系で、繊細なシルエットと宝石のような透明感が魅力の小型原種。",
    water: "生育期（春・秋）は土が完全に乾いたら充分に与える。夏・冬は頻度を下げ乾燥気味に。",
    temperature: "20〜25℃が理想。5℃以下は避ける。冬は室内管理。",
    placement: "年間を通じ明るい間接光の風通しのよい場所。強い直射日光、特に夏の西日は避ける。",
    soil: "多肉植物・サボテン用土。水はけ重視で軽石・鹿沼土混合推奨。",
    light: "足りない〜普通",
    lightBar: 40,
    lightDesc: "明るい間接光（500〜3000lux）",
    breeding: null,
    gallery: [],
  },
  {
    id: "turgida",
    name: "ツルギダ",
    scientific: "Haworthia turgida",
    type: "原種",
    accent: "#c4d8c4",
    description: "南アフリカ原産の軟葉系原種。ふっくらとした葉をロゼット状に広げ、強光・低温・水控えめで赤錆色に紅葉する。",
    water: "夏はやや湿り目を意識しながら土が乾いたらたっぷり。冬は乾かし気味に。過湿は厳禁。",
    temperature: "15〜20℃が理想。寒さには比較的強く、霜が当たらなければ屋外でも越冬可能。",
    placement: "明るい日陰〜半日陰。直射日光に弱いが、紅葉させたい場合は強めの間接光に当てる。",
    soil: "多肉植物用土。水はけよく赤玉土・軽石ベースが適切。",
    light: "普通",
    lightBar: 50,
    lightDesc: "紅葉させるには強めの光も有効（1000〜6000lux）",
    breeding: null,
    gallery: [],
  },
  {
    id: "soubi",
    name: "双眉",
    scientific: "Haworthia 'Soubi'",
    type: "園芸種",
    accent: "#d4e4d4",
    description: "葉の窓に眉を描いたような独特の模様が入ることが名の由来とされる軟葉系交配種。透明感と模様の繊細さが魅力。",
    water: "春・秋の生育期は土が乾いたら週1回たっぷり。夏・冬は月1〜2回に減らす。",
    temperature: "15〜20℃が理想。冬は5℃以上を保つ。急激な温度変化は避ける。",
    placement: "明るい室内の窓辺（直射日光を避けた間接光）。レースカーテン越しが理想。",
    soil: "多肉植物用の水はけのよい培養土。赤玉土・鹿沼土・軽石の混合配合が適切。",
    light: "足りない〜普通",
    lightBar: 35,
    lightDesc: "室内の明るい間接光（500〜3000lux）",
    breeding: null,
    gallery: [],
  },
];
